### ISSUE TITLE
Can not install on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by marek141017** [ungoogled-software/ungoogled-chromium-debian#161]
Hello
File name contains "focal2". What is this #2? 

dpkg -I ungoogled-chromium_83.0.4103.116-1.focal2_amd64.deb:

 Conflicts: libgl1-mesa-swx11, libnettle4, libsecret-1-0 (<< 0.18)
 Breaks: chromium, chromium-browser, chromium-lwn4chrome (<= 1.0-2), chromium-tt-rss-notifier (<= 0.5.2-2)

If I try to execute I got:
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 0x7ffde33a28e0#0 0x559fc6920919 (/usr/lib/chromium/chromium+0x42c3918)
Received signal 4 ILL_ILLOPN 559fc920c682
#0 0x559fc6920919 (/usr/lib/chromium/chromium+0x42c3918)
  r8: 0000000000000000  r9: 00007ffde33a1b60 r10: 0000000000000011 r11: 0000000000000000
 r12: 0000003000000008 r13: 00007ffde33a2bf0 r14: 0000559fc385a7e5 r15: 00007ffde33a2ba0
  di: 00007f6cab3984b0  si: 0000000000000000  bp: 00007ffde33a28d0  bx: 00007f6cab396780
  dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000001  sp: 00007ffde33a28d0
  ip: 0000559fc920c682 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated

Thank you.

**Comment by ghost** [comment]
I don't understand what issue you're having. But crashes are reportedly solved by latest builds.

**Comment by marek141017** [comment]
1 Issue:
The installation process ends with error about missing dependencies.
There is not any message though what are missing 
"apt-get install -f" simply removes app it doesn't fix anything

Also
 dpkg -I ungoogled-chromium_83.0.4103.116-1.focal2_amd64.deb:

Conflicts: libgl1-mesa-swx11, libnettle4, libsecret-1-0 (<< 0.18)
Breaks: chromium, chromium-browser, chromium-lwn4chrome (<= 1.0-2), chromium-tt-rss-notifier (<= 0.5.2-2)

I will check latest package
Thanks.

**Comment by ghost** [comment]
Yes, that's because the packaging scripts create multiple packages. The rest of them are in the repository.

**Comment by marek141017** [comment]
Do you mean in Ubuntu official repository or where?

**Comment by ghost** [comment]
It works correctly when installed from the OBS repository. Evidently we're going to need to write our own setup instructions since people keep getting it confused.

**Comment by marek141017** [comment]
You also may want to provide all packages that need to be installed.
Not just one *.deb. That may be more correctly, because some people may not want to add other repos.

**Comment by marek141017** [comment]
Okay
Yes, by adding your repository I managed to install 3 packages:
ungoogled-chromium* 
ungoogled-chromium-common* 
ungoogled-chromium-sandbox*

And it works

But I had to leave 71-st version, because it is the last version, where spell check works correctly in slack web app and some others.

In 83.0.4103.116 spell check in slack doesn't work at all. Even in google search page, i need to specially change the language to make spell check work.

Opera which also was build on 83-rd version does spell check correctly.

Thank you.
